MODEL_DECISION_APPROVE <- "Approve"
MODEL_DECISION_DECLINE <- "Decline"
MODEL_DECISION_MANUAL_REVIEW <- "Manual Review"

THICKNESS_NO_HIT <- "No Hit"
THICKNESS_THIN <- "Thin"
THICKNESS_THICK <- "Thick"